/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import DAO.BanDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.Ban;
import swing.scrollbar;
import swing.table;

/**
 *
 * @author VU HOANG
 */
public class frmChinhSuaBan extends javax.swing.JFrame {

    /**
     * Creates new form frmChinhSuaBan
     */
    public frmChinhSuaBan() {
        initComponents();
        spTable.setVerticalScrollBar(new scrollbar());
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        spTable.setVerticalScrollBar(new scrollbar());
        
        txtBanID.setHint("");
        txtTenBan.setHint("");
        setBackground(new Color(0,0,0,0));
        clear();
        loadData();
        
        txtSearch.setHint("Tìm kiếm theo vị trí bàn ...");
        txtSearch.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                loadDataFromSearch();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                loadDataFromSearch();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                loadDataFromSearch();
            }
            
            public void loadDataFromSearch(){
                clear();
                Ban a = new Ban();
                a.setB_VITRI(txtSearch.getText().trim());
                ArrayList<Ban> dsBan = BanDAO.timKiemDanhMucTheoTen(a);
                for(Ban ban: dsBan){
                    Vector info = new Vector();
                    info.add(ban.getB_SOBAN());
                    info.add(ban.getB_VITRI());

                    tblBan.addRow(info);
                }
            }
        }); 
    }
    
    public void showDetail(int pos){
        int id = (int) tblBan.getValueAt(pos, 0);
        String tenDm = (String) tblBan.getValueAt(pos, 1);
        
        txtBanID.setText(id + "");
        txtTenBan.setText(tenDm);
    }
    
    public void clear(){
        DefaultTableModel dtm = (DefaultTableModel) tblBan.getModel();
        dtm.setRowCount(0);
    }
    
    public void loadData(){
        clear();
        ArrayList<Ban> dsBan = BanDAO.layDanhSachBan();
        for(Ban ban: dsBan){
            Vector info = new Vector();
            info.add(ban.getB_SOBAN());
            info.add(ban.getB_VITRI());
            
            tblBan.addRow(info);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new swing.panelBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelBorder2 = new swing.panelBorder();
        spTable = new javax.swing.JScrollPane();
        tblBan = new swing.table();
        txtSearch = new swing.searchText();
        txtBanID = new swing.searchText();
        txtTenBan = new swing.searchText();
        btnXoa = new swing.button();
        btnThem = new swing.button();
        btnSua = new swing.button();
        btnBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form chỉnh sửa bàn");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder1.setMinimumSize(new java.awt.Dimension(910, 550));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Số bàn");
        panelBorder1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Vị trí");
        panelBorder1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        spTable.setBorder(null);

        tblBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số bàn", "Vị trí"
            }
        ));
        tblBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanMouseClicked(evt);
            }
        });
        tblBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblBanKeyReleased(evt);
            }
        });
        spTable.setViewportView(tblBan);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBorder1.add(panelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 880, 430));

        txtSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSearchInputMethodTextChanged(evt);
            }
        });
        panelBorder1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 420, 40));

        txtBanID.setEnabled(false);
        panelBorder1.add(txtBanID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, -1));
        panelBorder1.add(txtTenBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 410, -1));

        btnXoa.setText("Xóa");
        btnXoa.setBorderColor(new java.awt.Color(255, 69, 0));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        panelBorder1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, 30));

        btnThem.setText("Thêm");
        btnThem.setBorderColor(new java.awt.Color(255, 69, 0));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        panelBorder1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 30));

        btnSua.setText("Sửa");
        btnSua.setBorderColor(new java.awt.Color(255, 69, 0));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        panelBorder1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        panelBorder1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 8, -1, -1));

        getContentPane().add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanMouseClicked
        showDetail(((table)evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_tblBanMouseClicked

    private void tblBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBanKeyReleased
        showDetail(((table)evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_tblBanKeyReleased

    private void txtSearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSearchInputMethodTextChanged

    }//GEN-LAST:event_txtSearchInputMethodTextChanged

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int pos = tblBan.getSelectedRow();
        if(pos >= 0 && JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa bàn này", "Thông báo", JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION) {
            Ban ban = new Ban();
            int selectedID = (int) tblBan.getValueAt(pos, 0);
            ban.setB_SOBAN(selectedID);

            if(BanDAO.xoaBan(ban)) {
                JOptionPane.showMessageDialog(this, "Xóa bàn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Xóa bàn không thành công", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(txtTenBan.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vị trí bàn để thêm", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        loadData();
        int lastIndex = tblBan.getRowCount();
        int lastID = (int) tblBan.getValueAt(lastIndex - 1, 0);
        try {
            Ban ban = new Ban();
            ban.setB_SOBAN(lastID + 1);
            ban.setB_VITRI(txtTenBan.getText().trim());
            BanDAO.themBan(ban);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Không thêm được bàn", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        loadData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if(txtTenBan.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vị trí bàn để sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int pos = tblBan.getSelectedRow();
        if(pos >= 0){
            Ban ban = new Ban();
            int selectedID = (int) tblBan.getValueAt(pos, 0);
            ban.setB_SOBAN(selectedID);
            ban.setB_VITRI(txtTenBan.getText().trim());

            if(BanDAO.capNhatBan(ban)) {
                JOptionPane.showMessageDialog(this, "Cập nhật bàn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật bàn không thành công", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        loadData();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChinhSuaBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChinhSuaBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChinhSuaBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChinhSuaBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChinhSuaBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private swing.button btnSua;
    private swing.button btnThem;
    private swing.button btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private swing.panelBorder panelBorder1;
    private swing.panelBorder panelBorder2;
    private javax.swing.JScrollPane spTable;
    private swing.table tblBan;
    private swing.searchText txtBanID;
    private swing.searchText txtSearch;
    private swing.searchText txtTenBan;
    // End of variables declaration//GEN-END:variables
}
