/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import DAO.NhomQuyenDAO;
import DAO.NhomQuyen_NguoiDungDAO;
import DAO.PhanQuyenDAO;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import model.ComboBoxItem;
import model.NhomQuyen;
import model.Quyen;
import swing.scrollbar;

/**
 *
 * @author VU HOANG
 */
public class frmNhomQuyen extends javax.swing.JFrame {

    ItemListener itemListener;
    Boolean isAdd = false;
    Boolean isAdjust = false;
    /**
     * Creates new form frmNhomQuyen
     */
    public frmNhomQuyen() {
        initComponents();
        spTable.setVerticalScrollBar(new scrollbar());
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        spTable.setVerticalScrollBar(new scrollbar());
        
        txtNhomQuyenID.setHint("");
        txtTenNhomQuyen.setHint("");
        txtHienThi.setHint("");
        
        loadDataToCombobox();
        itemListener = new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e) {
                layThongTinNhomQuyen();
                loadData();
            }
        };
        cboNhomQuyen.addItemListener(itemListener);
        layThongTinNhomQuyen();
        loadData();
    }
    
    public void loadDataToCombobox(){
        cboNhomQuyen.removeAllItems();
        ArrayList<NhomQuyen> dsNhomQuyen = NhomQuyenDAO.layDanhSachNhomQuyen();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(NhomQuyen a : dsNhomQuyen){
            model.addElement(new ComboBoxItem(a.getNQ_TEN(), a.getNQ_HIENTHI()));
        }
        cboNhomQuyen.setModel(model);
    }
    
    public void clear(){
       DefaultTableModel dtm = (DefaultTableModel)tblBangTacDong.getModel();
       dtm.setRowCount(0);
    }
    
    public void loadData(){
        clear();
        ArrayList<String> dsBang = NhomQuyenDAO.layDanhSachCacBang();
        NhomQuyen nq = new NhomQuyen();
        nq.setNQ_ID(Integer.parseInt(txtNhomQuyenID.getText()));
        nq.setNQ_HIENTHI(txtHienThi.getText().trim());
        nq.setNQ_TEN(txtTenNhomQuyen.getText());
        for(String a : dsBang){
            Vector info = new Vector();
            info.add(a);
            Quyen quyen = new Quyen();
            quyen.setDIENGIAI("select on " + a);
            if(PhanQuyenDAO.kiemTraPhanQuyenChoNhom(quyen, nq)){
                info.add(true);
            } else {
                info.add(false);
            }
            quyen.setDIENGIAI("insert on " + a);
            if(PhanQuyenDAO.kiemTraPhanQuyenChoNhom(quyen, nq)){
                info.add(true);
            } else {
                info.add(false);
            }
            quyen.setDIENGIAI("delete on " + a);
            if(PhanQuyenDAO.kiemTraPhanQuyenChoNhom(quyen, nq)){
                info.add(true);
            } else {
                info.add(false);
            }
            quyen.setDIENGIAI("update on " + a);
            if(PhanQuyenDAO.kiemTraPhanQuyenChoNhom(quyen, nq)){
                info.add(true);
            } else {
                info.add(false);
            }
            tblBangTacDong.addRow(info);
        }
    }
    
    public void layThongTinNhomQuyen(){
        NhomQuyen nq = new NhomQuyen();
        nq.setNQ_HIENTHI(((ComboBoxItem)cboNhomQuyen.getSelectedItem()).getValue());
        NhomQuyen nhomQuyen = NhomQuyenDAO.layNhomQuyenTheoHienThi(nq);
        txtNhomQuyenID.setText(nhomQuyen.getNQ_ID() + "");
        txtTenNhomQuyen.setText(nhomQuyen.getNQ_TEN());
        txtHienThi.setText(nhomQuyen.getNQ_HIENTHI());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new swing.panelBorder();
        btnBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNhomQuyenID = new swing.searchText();
        jLabel2 = new javax.swing.JLabel();
        txtTenNhomQuyen = new swing.searchText();
        jLabel3 = new javax.swing.JLabel();
        txtHienThi = new swing.searchText();
        btnThemNQ = new swing.button();
        btnXoaNQ = new swing.button();
        cboNhomQuyen = new swing.combobox();
        panelBorder2 = new swing.panelBorder();
        spTable = new javax.swing.JScrollPane();
        tblBangTacDong = new swing.table();
        btnGanQuyen = new swing.button();
        btnLuu = new swing.button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhóm quyền ID");

        txtNhomQuyenID.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên nhóm quyền");

        txtTenNhomQuyen.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hiển thị");

        txtHienThi.setEnabled(false);

        btnThemNQ.setText("Thêm");
        btnThemNQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNQActionPerformed(evt);
            }
        });

        btnXoaNQ.setText("Xóa");
        btnXoaNQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNQActionPerformed(evt);
            }
        });

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        spTable.setBorder(null);

        tblBangTacDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bảng", "Xem", "Thêm", "Xóa", "Sửa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(tblBangTacDong);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnGanQuyen.setText("Gán quyền");
        btnGanQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanQuyenActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelBorder1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNhomQuyenID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTenNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                                        .addComponent(btnThemNQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)
                                        .addComponent(btnXoaNQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(138, 138, 138)))
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelBorder1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(cboNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(btnGanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNhomQuyenID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnThemNQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNQActionPerformed
        txtNhomQuyenID.setText(NhomQuyenDAO.layMaTiepTheoCuaNhomQuyen() + "");
        txtTenNhomQuyen.setEnabled(true);
        txtHienThi.setEnabled(true);
        txtTenNhomQuyen.setText("");
        txtHienThi.setText("");
        isAdd = true;
    }//GEN-LAST:event_btnThemNQActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(txtTenNhomQuyen.getText().trim().length() * txtHienThi.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ các trường", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(txtTenNhomQuyen.getText().trim().contains(" ")){
            JOptionPane.showMessageDialog(this, "Tên nhóm quyền không chứa khoảng trắng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        NhomQuyen nq = new NhomQuyen();
        nq.setNQ_ID(Integer.parseInt(txtNhomQuyenID.getText()));
        nq.setNQ_HIENTHI(txtHienThi.getText().trim());
        nq.setNQ_TEN(txtTenNhomQuyen.getText());
        if(NhomQuyenDAO.kiemTraTrungTenNhomQuyen(nq) || NhomQuyenDAO.kiemTraTrungHienThi(nq)){
            JOptionPane.showMessageDialog(this, "Đã trùng nhóm quyền vui lòng chọn lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(isAdd){
            NhomQuyenDAO.themNhomQuyen(nq);
            NhomQuyenDAO.themNhomQuyenDatabase(nq);
            isAdd = false;
            JOptionPane.showMessageDialog(this, "Thêm nhóm quyền thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
        }
        cboNhomQuyen.removeItemListener(itemListener);
        txtTenNhomQuyen.setEnabled(false);
        txtHienThi.setEnabled(false);
        loadDataToCombobox();
        cboNhomQuyen.addItemListener(itemListener);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaNQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNQActionPerformed
        NhomQuyen nq = new NhomQuyen();
        nq.setNQ_ID(Integer.parseInt(txtNhomQuyenID.getText()));
        nq.setNQ_HIENTHI(txtHienThi.getText().trim());
        nq.setNQ_TEN(txtTenNhomQuyen.getText());
        if(NhomQuyen_NguoiDungDAO.kiemTraNhomQuyenDaPhanChoNguoiDung(nq)){
            JOptionPane.showMessageDialog(this, "Nhóm quyền " + nq.getNQ_HIENTHI() + " đã được phân cho người dùng nên không thể xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa nhóm quyền " + nq.getNQ_HIENTHI(), "Thông báo", JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION){
            NhomQuyenDAO.xoaCapQuyenTheoNhomQuyen(nq);
            NhomQuyen_NguoiDungDAO.xoaNhomQuyenNguoiDungTheoNhomQuyen(nq);
            NhomQuyenDAO.xoaNhomQuyenDatabase(nq);
            NhomQuyenDAO.xoaNhomQuyen(nq);
            cboNhomQuyen.removeItemListener(itemListener);
            loadDataToCombobox();
            cboNhomQuyen.addItemListener(itemListener);
            JOptionPane.showMessageDialog(this, "Xóa danh mục thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaNQActionPerformed

    private void btnGanQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanQuyenActionPerformed
        for(int i = 0 ; i < tblBangTacDong.getRowCount() ; i++){
            Quyen q = new Quyen();
            NhomQuyen nq = new NhomQuyen();
            nq.setNQ_ID(Integer.parseInt(txtNhomQuyenID.getText()));
            nq.setNQ_HIENTHI(txtHienThi.getText().trim());
            nq.setNQ_TEN(txtTenNhomQuyen.getText());
            
            q.setDIENGIAI("select on " + tblBangTacDong.getValueAt(i, 0).toString());
            if(Boolean.valueOf(tblBangTacDong.getValueAt(i, 1) + "")){
                if(!NhomQuyenDAO.kiemTraNhomDaCoQuyen(q, nq)){
                    NhomQuyenDAO.capQuyenChoNhom(q, nq);
                    NhomQuyenDAO.capQuyenChoNhomDatabase(q, nq);
                }
            } else {
                NhomQuyenDAO.xoaQuyenCuaNhom(q, nq);
                NhomQuyenDAO.xoaQuyenCuaNhomDatabase(q, nq);
            }
            
            q.setDIENGIAI("insert on " + tblBangTacDong.getValueAt(i, 0).toString());
            if(Boolean.valueOf(tblBangTacDong.getValueAt(i, 2) + "")){
                if(!NhomQuyenDAO.kiemTraNhomDaCoQuyen(q, nq)){
                    NhomQuyenDAO.capQuyenChoNhom(q, nq);
                    NhomQuyenDAO.capQuyenChoNhomDatabase(q, nq);
                }
            } else {
                NhomQuyenDAO.xoaQuyenCuaNhom(q, nq);
                NhomQuyenDAO.xoaQuyenCuaNhomDatabase(q, nq);
            }
            
            q.setDIENGIAI("delete on " + tblBangTacDong.getValueAt(i, 0).toString());
            if(Boolean.valueOf(tblBangTacDong.getValueAt(i, 3) + "")){
                if(!NhomQuyenDAO.kiemTraNhomDaCoQuyen(q, nq)){
                    NhomQuyenDAO.capQuyenChoNhom(q, nq);
                    NhomQuyenDAO.capQuyenChoNhomDatabase(q, nq);
                }
            } else {
                NhomQuyenDAO.xoaQuyenCuaNhom(q, nq);
                NhomQuyenDAO.xoaQuyenCuaNhomDatabase(q, nq);
            }
            
            q.setDIENGIAI("update on " + tblBangTacDong.getValueAt(i, 0).toString());
            if(Boolean.valueOf(tblBangTacDong.getValueAt(i, 4) + "")){
                if(!NhomQuyenDAO.kiemTraNhomDaCoQuyen(q, nq)){
                    NhomQuyenDAO.capQuyenChoNhom(q, nq);
                    NhomQuyenDAO.capQuyenChoNhomDatabase(q, nq);
                }
            } else {
                NhomQuyenDAO.xoaQuyenCuaNhom(q, nq);
                NhomQuyenDAO.xoaQuyenCuaNhomDatabase(q, nq);
            }
        }
        JOptionPane.showMessageDialog(this, "Gán quyền cho nhóm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGanQuyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhomQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhomQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhomQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhomQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhomQuyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private swing.button btnGanQuyen;
    private swing.button btnLuu;
    private swing.button btnThemNQ;
    private swing.button btnXoaNQ;
    private swing.combobox cboNhomQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private swing.panelBorder panelBorder1;
    private swing.panelBorder panelBorder2;
    private javax.swing.JScrollPane spTable;
    private swing.table tblBangTacDong;
    private swing.searchText txtHienThi;
    private swing.searchText txtNhomQuyenID;
    private swing.searchText txtTenNhomQuyen;
    // End of variables declaration//GEN-END:variables
}
